### ISSUE TITLE
Brands want to easily add detailed survey configuration 

### ISSUE THREAD

**Issue by arg0s** [getcloudcherry/cloudcherry-android-sdk#6]
We want to easily add survey configuration
And set it up for static survey token details
And optionally set it up by dynamically fetching survey token details
And optionally setting up any pre-fill information required
And optionally setting up any location or tag information required

**Comment by Femilshajin** [comment]
Brands should be able to Prefill customer information which they already possess and don't want to ask it again such as name, email, mobile, etc.

We can pass a keyvaluepair type as a parameter while initializing the SDK, where a key is the 'tag' and 'Value' is the response, Iterate through questions and find the question against tag prefill the response and add it to the 'RecordAnswer'. If Tag is not found ignore, else prefill.

**Comment by rohithveerajappa** [comment]
Hi Femil

The SDK-prefill has been handled.
1. User adds question-tags while creating questions on the CC dashboard.
2. After initialising SDK, developer send key-value hashmap to SurveyCC.getInstance().setPreFill()
3. Key would be one of the question-tags.      Value would be the answer to be pre-filled.
